version: '3'
services:
  openjdk:
    image: openjdk:7
    # working_dir: /app
    # ports:
    #   - "8088:8080"
    volumes:
      - ./jdapi:/usr/src/myapp
    # command: "/bin/sh -c while true;do echo hello docker;sleep 1;done;"
    